version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean install
      - codecov/upload
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - target/*.jar

workflows:
  sample:
    jobs:
      - build-and-test
