version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
  aws-ecr: circleci/aws-ecr@6.7.0
jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B clean install
      - codecov/upload
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: parking-lot-api

workflows:
  sample:
    jobs:
      - build-and-test
